defmodule TravelingPoetWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :traveling_poet

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `max_age` makes it outlive the browser session. Without it the cookie dies
  # with the process that holds it, and iOS ends an app's process whenever it
  # likes: readers in the app were signed out every time that happened.
  # `UserAuth.fetch_current_user/2` re-issues the cookie as it ages, so the
  # 180 days run from the last visit, not from the sign-in.
  @session_options [
    store: :cookie,
    key: "_traveling_poet_key",
    signing_salt: "dh9YZzyZ",
    same_site: "Lax",
    max_age: 180 * 24 * 60 * 60
  ]

  # `:user_agent` is how a LiveView tells the iOS app from a browser
  # (Plugs.NativeApp), and what a push subscription is labelled with.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:user_agent, session: @session_options]],
    longpoll: [connect_info: [:user_agent, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :traveling_poet,
    gzip: not code_reloading?,
    only: TravelingPoetWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :traveling_poet
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # keeps raw bytes for /webhooks/* (Stripe signature verification)
    body_reader: {TravelingPoetWeb.Plugs.CacheBodyReader, :read_body, []},
    # base64 illustration uploads on /api/agent/media run ~8MB
    length: 12_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TravelingPoetWeb.Router
end
